# Generated by Django 2.2.5 on 2020-06-01 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('noti_type', models.CharField(choices=[('댓글을 달았습니다.', '댓글을 달았습니다.'), ('좋아요를 눌렀습니다.', '좋아요를 눌렀습니다.')], default='좋아요를 눌렀습니다.', max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_notifications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
