# Generated by Django 2.2.5 on 2020-07-29 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('noti_type', models.CharField(choices=[('댓글', '댓글'), ('좋아요', '좋아요'), ('싫어요', '싫어요'), ('좋아요취소', '좋아요취소'), ('싫어요취소', '싫어요취소'), ('댓글좋아요', '댓글좋아요'), ('댓글좋아요취소', '댓글좋아요취소'), ('댓글싫어요', '댓글싫어요'), ('댓글싫어요취소', '댓글싫어요취소')], default='좋아요', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
