# Generated by Django 2.2.5 on 2020-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200601_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('댓글', '댓글'), ('좋아요', '좋아요'), ('싫어요', '싫어요'), ('좋아요취소', '좋아요취소'), ('싫어요취소', '싫어요취소'), ('댓글좋아요', '댓글좋아요'), ('댓글좋아요취소', '댓글좋아요취소'), ('댓글싫어요', '댓글싫어요'), ('댓글싫어요취소', '댓글싫어요취소')], default='좋아요', max_length=20),
        ),
    ]
