# Generated by Django 2.2.5 on 2020-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='date',
        ),
        migrations.AddField(
            model_name='vacation',
            name='calendar_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', 4)], default='1', max_length=3),
        ),
    ]
