# Generated by Django 2.2.5 on 2020-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_auto_20200604_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='date',
            field=models.CharField(default='0000-00-00', max_length=8),
        ),
    ]
